package view.SDI;

import model.Estudante;
import repository.EstudanteDAO;

public class ConsultaEstudanteSDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaEstudanteSDI.class.getName());

    public ConsultaEstudanteSDI() {
        initComponents();
        // Configurações visuais e estado inicial (Fora do initComponents para proteger o Design)
        getContentPane().setBackground(
            new java.awt.Color(244, 247, 250)
        );

        java.awt.Color azul = new java.awt.Color(22, 105, 122);

        consultar.setBackground(azul);
        consultar.setForeground(java.awt.Color.WHITE);

        fechar.setBackground(azul);
        fechar.setForeground(java.awt.Color.WHITE);
        
        limpar.setBackground(azul);
        limpar.setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtSemestre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        cmbSituacao1 = new javax.swing.JComboBox<>();
        txtSemestre1 = new javax.swing.JTextField();
        txtCurso1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        cmbSituacao2 = new javax.swing.JComboBox<>();
        txtTelefone1 = new javax.swing.JTextField();
        txtMatricula1 = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbNome = new javax.swing.JRadioButton();
        txtConsulta = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        rbMatricula = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMatriculaconsulta = new javax.swing.JTextField();
        txtNomeconsulta = new javax.swing.JTextField();
        txtCursoconsulta = new javax.swing.JTextField();
        txtSemestreconsulta = new javax.swing.JTextField();
        txtEmailconsulta = new javax.swing.JTextField();
        txtTelefoneconsulta = new javax.swing.JTextField();
        cmbSituacao = new javax.swing.JComboBox<>();
        limpar = new javax.swing.JButton();
        fechar = new javax.swing.JToggleButton();

        txtMatricula.setEditable(false);
        txtMatricula.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtNome.setEditable(false);
        txtNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtCurso.setEditable(false);
        txtCurso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtSemestre.setEditable(false);
        txtSemestre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtTelefone.setEditable(false);
        txtTelefone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        cmbSituacao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Formado", "Trancado", "Evadido", "Jubilado" }));
        cmbSituacao1.addActionListener(this::cmbSituacao1ActionPerformed);

        txtSemestre1.setEditable(false);
        txtSemestre1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtCurso1.setEditable(false);
        txtCurso1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtEmail1.setEditable(false);
        txtEmail1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        cmbSituacao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Formado", "Trancado", "Evadido", "Jubilado" }));
        cmbSituacao2.addActionListener(this::cmbSituacao2ActionPerformed);

        txtTelefone1.setEditable(false);
        txtTelefone1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtMatricula1.setEditable(false);
        txtMatricula1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtNome1.setEditable(false);
        txtNome1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Estudante");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(22, 105, 122))); // NOI18N

        buttonGroup1.add(rbNome);
        rbNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rbNome.setText("Nome");
        rbNome.addActionListener(this::rbNomeActionPerformed);

        consultar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        consultar.setText("Consultar");
        consultar.setPreferredSize(new java.awt.Dimension(64, 22));
        consultar.addActionListener(this::consultarActionPerformed);

        buttonGroup1.add(rbMatricula);
        rbMatricula.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rbMatricula.setText("Matrícula");
        rbMatricula.addActionListener(this::rbMatriculaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtConsulta))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Curso");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Semestre");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Situação");

        txtMatriculaconsulta.setEditable(false);
        txtMatriculaconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        txtNomeconsulta.setEditable(false);
        txtNomeconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        txtCursoconsulta.setEditable(false);
        txtCursoconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        txtSemestreconsulta.setEditable(false);
        txtSemestreconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        txtEmailconsulta.setEditable(false);
        txtEmailconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        txtTelefoneconsulta.setEditable(false);
        txtTelefoneconsulta.setMaximumSize(new java.awt.Dimension(50, 22));

        cmbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Formado", "Trancado", "Evadido", "Jubilado" }));
        cmbSituacao.setMaximumSize(new java.awt.Dimension(50, 22));
        cmbSituacao.addActionListener(this::cmbSituacaoActionPerformed);

        limpar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.setToolTipText("");
        limpar.addActionListener(this::limparActionPerformed);

        fechar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(this::fecharActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpar)
                        .addGap(30, 30, 30)
                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCursoconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMatriculaconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomeconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefoneconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSemestreconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmailconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(135, 135, 135))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fechar, limpar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMatriculaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCursoconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSemestreconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefoneconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechar)
                    .addComponent(limpar))
                .addGap(15, 15, 15))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fechar, limpar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        String busca = txtConsulta.getText().trim();

        if (busca.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite o termo de busca na caixa de texto.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
             return;
        }

        try {
            EstudanteDAO dao = new EstudanteDAO();
            java.util.List<Estudante> estudantes = dao.consultar(busca);

            if (estudantes.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Estudante não encontrado!");
                return;
            }

            Estudante estudante = estudantes.get(0);

            txtMatriculaconsulta.setText(estudante.getMatricula());
            txtNomeconsulta.setText(estudante.getNome());
            txtCursoconsulta.setText(estudante.getCurso());
            txtSemestreconsulta.setText(String.valueOf(estudante.getSemestre()));
            txtEmailconsulta.setText(estudante.getEmail());
            txtTelefoneconsulta.setText(estudante.getTelefone());
            cmbSituacao.setSelectedItem(estudante.getSituacao());

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void cmbSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSituacaoActionPerformed

    private void rbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatriculaActionPerformed
        txtConsulta.setText("");
        txtConsulta.setToolTipText("Digite a matrícula para consultar");
        txtConsulta.requestFocus();
    }//GEN-LAST:event_rbMatriculaActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        txtConsulta.setText("");
        txtConsulta.setToolTipText("Digite o nome para consultar");
        txtConsulta.requestFocus();
    }//GEN-LAST:event_rbNomeActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtMatriculaconsulta.setText("");
        txtNomeconsulta.setText("");
        txtCursoconsulta.setText("");
        txtSemestreconsulta.setText("");
        txtEmailconsulta.setText("");
        txtTelefoneconsulta.setText("");
        cmbSituacao.setSelectedIndex(0);
        txtConsulta.setText("");
        txtConsulta.requestFocus();
    }//GEN-LAST:event_limparActionPerformed

    private void cmbSituacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSituacao1ActionPerformed

    }//GEN-LAST:event_cmbSituacao1ActionPerformed

    private void cmbSituacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSituacao2ActionPerformed

    }//GEN-LAST:event_cmbSituacao2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaEstudanteSDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbSituacao;
    private javax.swing.JComboBox<String> cmbSituacao1;
    private javax.swing.JComboBox<String> cmbSituacao2;
    private javax.swing.JButton consultar;
    private javax.swing.JToggleButton fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpar;
    private javax.swing.JRadioButton rbMatricula;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtCurso1;
    private javax.swing.JTextField txtCursoconsulta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmailconsulta;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatricula1;
    private javax.swing.JTextField txtMatriculaconsulta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNomeconsulta;
    private javax.swing.JTextField txtSemestre;
    private javax.swing.JTextField txtSemestre1;
    private javax.swing.JTextField txtSemestreconsulta;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefoneconsulta;
    // End of variables declaration//GEN-END:variables
}
