package view.MDI;
import model.Estudante;
import repository.EstudanteDAO;

public class CadastroEstudanteMDI extends javax.swing.JInternalFrame {
    public CadastroEstudanteMDI() {
        initComponents();
        getContentPane().setBackground(
        new java.awt.Color(248, 250, 251)
        );
        getContentPane().setBackground(
        new java.awt.Color(244, 247, 250)
        );
        // Fundo da tela
        getContentPane().setBackground(
            new java.awt.Color(244, 247, 250)
        );

        java.awt.Color azul = new java.awt.Color(22, 105, 122);

        limpar.setBackground(azul);
        limpar.setForeground(java.awt.Color.WHITE);

        cadastrar.setBackground(azul);
        cadastrar.setForeground(java.awt.Color.WHITE);

        fechar.setBackground(azul);
        fechar.setForeground(java.awt.Color.WHITE);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblMatricula = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        cmbSituacao = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblMatricula.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMatricula.setText("Matrícula");

        lblNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        lblCurso.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCurso.setText("Curso");

        lblSemestre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSemestre.setText("Semestre");

        lblEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        lblTelefone.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone");

        lblSituacao.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSituacao.setText("Situação");

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtMatricula.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtCurso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCurso.addActionListener(this::txtCursoActionPerformed);

        txtTelefone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTelefone.addActionListener(this::txtTelefoneActionPerformed);

        limpar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.setToolTipText("");
        limpar.addActionListener(this::limparActionPerformed);

        cadastrar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.setToolTipText("");
        cadastrar.addActionListener(this::cadastrarActionPerformed);

        fechar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        fechar.setText("Fechar");
        fechar.setToolTipText("");
        fechar.addActionListener(this::fecharActionPerformed);

        lblTitulo.setBackground(new java.awt.Color(22, 105, 122));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(22, 105, 122));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Estudante");

        txtSemestre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        cmbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Formado", "Trancado", "Evadido", "Jubilado" }));
        cmbSituacao.addActionListener(this::cmbSituacaoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSituacao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSemestre)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail)))
                            .addGap(271, 448, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMatricula)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMatricula)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbSituacao, javax.swing.GroupLayout.Alignment.LEADING, 0, 233, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                        .addComponent(txtSemestre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrar)
                                .addGap(36, 36, 36)
                                .addComponent(limpar)
                                .addGap(37, 37, 37)
                                .addComponent(fechar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbSituacao, txtCurso, txtEmail, txtMatricula, txtNome, txtSemestre, txtTelefone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTitulo)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatricula)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurso)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemestre)
                            .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSituacao)
                            .addComponent(cmbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(limpar)
                    .addComponent(fechar))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbSituacao, txtCurso, txtEmail, txtMatricula, txtNome, txtSemestre, txtTelefone});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtMatricula.setText("");
        txtNome.setText("");
        txtCurso.setText("");
        txtSemestre.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        cmbSituacao.setSelectedIndex(0);
    }//GEN-LAST:event_limparActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String matricula = txtMatricula.getText();
        String nome = txtNome.getText();
        String curso = txtCurso.getText();
        String semestreTexto = txtSemestre.getText();
        String email = txtEmail.getText();
        String telefone = txtTelefone.getText();
        String situacao = cmbSituacao.getSelectedItem().toString();

        try {
            Integer semestre = Integer.valueOf(semestreTexto);

            Estudante estudante = new Estudante();

            estudante.setMatricula(matricula);
            estudante.setNome(nome);
            estudante.setCurso(curso);
            estudante.setSemestre(semestre);
            estudante.setEmail(email);
            estudante.setTelefone(telefone);
            estudante.setSituacao(situacao);

            EstudanteDAO dao = new EstudanteDAO();
            dao.inserir(estudante);

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Estudante cadastrado com sucesso!"
            );

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "O semestre deve ser um número."
            );
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void cmbSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSituacaoActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JComboBox<String> cmbSituacao;
    private javax.swing.JButton fechar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSemestre;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
