package view.MDI;

public class PrincipalMDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalMDI.class.getName());

    public PrincipalMDI() {
        initComponents();
        java.awt.Color azul = new java.awt.Color(72, 159, 181);
        jDesktopPane9.setBackground(new java.awt.Color(248, 250, 251));

        menu.setOpaque(true);
        menu.setBorderPainted(false);
        menu.setUI(new javax.swing.plaf.basic.BasicMenuBarUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                g.setColor(azul);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });

        cadastro.setForeground(java.awt.Color.WHITE);
        consulta.setForeground(java.awt.Color.WHITE);
        relatorio.setForeground(java.awt.Color.WHITE);
        sistema.setForeground(java.awt.Color.WHITE);

        cadastro.setMargin(new java.awt.Insets(5, 25, 5, 25));
        consulta.setMargin(new java.awt.Insets(5, 25, 5, 25));
        relatorio.setMargin(new java.awt.Insets(5, 25, 5, 25));
        sistema.setMargin(new java.awt.Insets(5, 25, 5, 25));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Alterar = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();
        consulta = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        Listar = new javax.swing.JMenuItem();
        sistema = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Sistema Acadêmico - MDI"); // NOI18N

        jDesktopPane9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(22, 105, 122));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 105, 122));
        jLabel5.setText("Sistema Acadêmico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 226, 230)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 190));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 105, 122));
        jLabel7.setText("Bem-vindo ao Sistema Acadêmico!");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(5, 85, 85));
        jLabel8.setText("de forma simples e organizada.");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(5, 85, 85));
        jLabel10.setText("Gerencie os dados dos estudantes ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel7)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(78, 78, 78))
        );

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 74, 74));
        jLabel6.setText("Gerenciamento de Estudantes");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(72, 159, 181));
        jLabel9.setText("Selecione uma opção do menu");

        jDesktopPane9.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane9Layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(jLabel6))
                    .addGroup(jDesktopPane9Layout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(jLabel5))
                    .addGroup(jDesktopPane9Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane9Layout.createSequentialGroup()
                        .addGap(569, 569, 569)
                        .addComponent(jLabel9)))
                .addContainerGap(1091, Short.MAX_VALUE))
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(22, 105, 122));
        menu.setMargin(new java.awt.Insets(5, 15, 5, 15));
        menu.setOpaque(true);

        cadastro.setForeground(new java.awt.Color(255, 255, 255));
        cadastro.setText("Cadastro");
        cadastro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        Cadastrar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Cadastrar.setText("Cadastrar Estudante");
        Cadastrar.addActionListener(this::CadastrarActionPerformed);
        cadastro.add(Cadastrar);

        Alterar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Alterar.setText("Alterar Estudante");
        Alterar.setActionCommand("");
        Alterar.addActionListener(this::AlterarActionPerformed);
        cadastro.add(Alterar);

        Excluir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Excluir.setText("Excluir Estudante");
        Excluir.addActionListener(this::ExcluirActionPerformed);
        cadastro.add(Excluir);

        menu.add(cadastro);

        consulta.setForeground(new java.awt.Color(255, 255, 255));
        consulta.setText("Consulta");
        consulta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        Consultar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Consultar.setText("Consultar Estudante");
        Consultar.addActionListener(this::ConsultarActionPerformed);
        consulta.add(Consultar);

        menu.add(consulta);

        relatorio.setText("Relatório");
        relatorio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        Listar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Listar.setText("Listar Estudante");
        Listar.addActionListener(this::ListarActionPerformed);
        relatorio.add(Listar);

        menu.add(relatorio);

        sistema.setForeground(new java.awt.Color(255, 255, 255));
        sistema.setText("Sistema");
        sistema.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        Sobre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Sobre.setText("Sobre");
        Sobre.addActionListener(this::SobreActionPerformed);
        sistema.add(Sobre);

        Sair.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(this::SairActionPerformed);
        sistema.add(Sair);

        menu.add(sistema);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        SobreSistemaMDI tela = new SobreSistemaMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_SobreActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        ListaEstudanteMDI tela = new ListaEstudanteMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ListarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        ConsultaEstudanteMDI tela = new ConsultaEstudanteMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        ExcluirEstudanteMDI tela = new ExcluirEstudanteMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        AlterarEstudanteMDI tela = new AlterarEstudanteMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_AlterarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        CadastroEstudanteMDI tela = new CadastroEstudanteMDI();
        jDesktopPane9.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalMDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu consulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu relatorio;
    private javax.swing.JMenu sistema;
    // End of variables declaration//GEN-END:variables
}
